service: tm-demo
description: "serverless.yaml deployment test"

provider:
  name: triggermesh
  environment:
    FOO: BAR

functions:
  go-openfaas:
    source: go-openfaas/main.go
    runtime: https://raw.githubusercontent.com/triggermesh/openfaas-runtime/master/go/openfaas-go-runtime.yaml
    environment:
      FUNCTION: bar

  go-lambda:
    source: go-lambda/main.go
    runtime: https://raw.githubusercontent.com/triggermesh/knative-lambda-runtime/master/go-1.x/runtime.yaml
    environment:
      foo: bar
    
  nodejs-openfaas:
    source: https://github.com/openfaas/faas
    runtime: https://raw.githubusercontent.com/triggermesh/openfaas-runtime/master/openfaas/nodejs-runtime.yaml
    description: "nodejs fragment"
    buildargs:
      - DIRECTORY=sample-functions/BaseFunctions/node
    environment:
      FUNCTION: nodejs

  nodejs-lambda:
    source: nodejs-lambda/handler.js
    runtime: https://raw.githubusercontent.com/triggermesh/knative-lambda-runtime/master/node-10.x/runtime.yaml
    buildargs:
    - HANDLER=handler.sayHelloAsync
    environment:
      foo: bar

include:
  - python-lambda/serverless.yaml
  - https://github.com/tzununbekov/serverless-include
