service: serverless-foo
description: "serverless.yaml parsing test"

provider:
  name: triggermesh
  runtime: https://raw.githubusercontent.com/triggermesh/openfaas-runtime/master/go/openfaas-go-runtime.yaml
  environment:
    FOO: BAR

functions:
  bar:
    handler: bar/main.go
    environment:
      FUNCTION: bar

#  nodejs:
#    handler: https://github.com/openfaas/serverless-openfaas-nodejs
#    runtime: https://raw.githubusercontent.com/triggermesh/openfaas-runtime/master/nodejs/openfaas-nodejs-runtime.yaml
#    description: "nodejs fragment"
#    buildargs:
#      - DIRECTORY=hello-world
#    environment:
#      FUNCTION: nodejs

  remote:
    handler: https://gitlab.com/tzununbekov/tesfunc
    revision: master
    description: "Go function with another repository as source"
    environment:
      FUNCTION: remote

include:
#  - foo/single-function.yaml
  - https://github.com/tzununbekov/serverless-include
